[System.Serializable]
public struct Spaces
{
    public bool this[int i] => Get(i);

    public bool Get(int i)
    {
        i = i + 1;
        if (i < 1 || i > 49) return false;

        if (i == 1) return space1;
        else if (i == 2) return space2;
        else if (i == 3) return space3;
        else if (i == 4) return space4;
        else if (i == 5) return space5;
        else if (i == 6) return space6;
        else if (i == 7) return space7;
        else if (i == 8) return space8;
        else if (i == 9) return space9;
        else if (i == 10) return space10;
        else if (i == 11) return space11;
        else if (i == 12) return space12;
        else if (i == 13) return space13;
        else if (i == 14) return space14;
        else if (i == 15) return space15;
        else if (i == 16) return space16;
        else if (i == 17) return space17;
        else if (i == 18) return space18;
        else if (i == 19) return space19;
        else if (i == 20) return space20;
        else if (i == 21) return space21;
        else if (i == 22) return space22;
        else if (i == 23) return space23;
        else if (i == 24) return space24;
        else if (i == 25) return space25;
        else if (i == 26) return space26;
        else if (i == 27) return space27;
        else if (i == 28) return space28;
        else if (i == 29) return space29;
        else if (i == 30) return space30;
        else if (i == 31) return space31;
        else if (i == 32) return space32;
        else if (i == 33) return space33;
        else if (i == 34) return space34;
        else if (i == 35) return space35;
        else if (i == 36) return space36;
        else if (i == 37) return space37;
        else if (i == 38) return space38;
        else if (i == 39) return space39;
        else if (i == 40) return space40;
        else if (i == 41) return space41;
        else if (i == 42) return space42;
        else if (i == 43) return space43;
        else if (i == 44) return space44;
        else if (i == 45) return space45;
        else if (i == 46) return space46;
        else if (i == 47) return space47;
        else if (i == 48) return space48;
        else if (i == 49) return space49;
        return false;
    }
    public void Assign(Spaces other)
    {
        space1 = other.space1;
        space2 = other.space2;
        space3 = other.space3;
        space4 = other.space4;
        space5 = other.space5;
        space6 = other.space6;
        space7 = other.space7;
        space8 = other.space8;
        space9 = other.space9;
        space10 = other.space10;
        space11 = other.space11;
        space12 = other.space12;
        space13 = other.space13;
        space14 = other.space14;
        space15 = other.space15;
        space16 = other.space16;
        space17 = other.space17;
        space18 = other.space18;
        space19 = other.space19;
        space20 = other.space20;
        space21 = other.space21;
        space22 = other.space22;
        space23 = other.space23;
        space24 = other.space24;
        space25 = other.space25;
        space26 = other.space26;
        space27 = other.space27;
        space28 = other.space28;
        space29 = other.space29;
        space30 = other.space30;
        space31 = other.space31;
        space32 = other.space32;
        space33 = other.space33;
        space34 = other.space34;
        space35 = other.space35;
        space36 = other.space36;
        space37 = other.space37;
        space38 = other.space38;
        space39 = other.space39;
        space40 = other.space40;
        space41 = other.space41;
        space42 = other.space42;
        space43 = other.space43;
        space44 = other.space44;
        space45 = other.space45;
        space46 = other.space46;
        space47 = other.space47;
        space48 = other.space48;
        space49 = other.space49;
    }

    public void Reset()
    {
        space1 = false;
        space2 = false;
        space3 = false;
        space4 = false;
        space5 = false;
        space6 = false;
        space7 = false;
        space8 = false;
        space9 = false;
        space10 = false;
        space11 = false;
        space12 = false;
        space13 = false;
        space14 = false;
        space15 = false;
        space16 = false;
        space17 = false;
        space18 = false;
        space19 = false;
        space20 = false;
        space21 = false;
        space22 = false;
        space23 = false;
        space24 = false;
        space25 = false;
        space26 = false;
        space27 = false;
        space28 = false;
        space29 = false;
        space30 = false;
        space31 = false;
        space32 = false;
        space33 = false;
        space34 = false;
        space35 = false;
        space36 = false;
        space37 = false;
        space38 = false;
        space39 = false;
        space40 = false;
        space41 = false;
        space42 = false;
        space43 = false;
        space44 = false;
        space45 = false;
        space46 = false;
        space47 = false;
        space48 = false;
        space49 = false;
    }

    public Spaces(Spaces other)
    {
        space1 = other.space1;
        space2 = other.space2;
        space3 = other.space3;
        space4 = other.space4;
        space5 = other.space5;
        space6 = other.space6;
        space7 = other.space7;
        space8 = other.space8;
        space9 = other.space9;
        space10 = other.space10;
        space11 = other.space11;
        space12 = other.space12;
        space13 = other.space13;
        space14 = other.space14;
        space15 = other.space15;
        space16 = other.space16;
        space17 = other.space17;
        space18 = other.space18;
        space19 = other.space19;
        space20 = other.space20;
        space21 = other.space21;
        space22 = other.space22;
        space23 = other.space23;
        space24 = other.space24;
        space25 = other.space25;
        space26 = other.space26;
        space27 = other.space27;
        space28 = other.space28;
        space29 = other.space29;
        space30 = other.space30;
        space31 = other.space31;
        space32 = other.space32;
        space33 = other.space33;
        space34 = other.space34;
        space35 = other.space35;
        space36 = other.space36;
        space37 = other.space37;
        space38 = other.space38;
        space39 = other.space39;
        space40 = other.space40;
        space41 = other.space41;
        space42 = other.space42;
        space43 = other.space43;
        space44 = other.space44;
        space45 = other.space45;
        space46 = other.space46;
        space47 = other.space47;
        space48 = other.space48;
        space49 = other.space49;
    }

    public bool space1;
    public bool space2;
    public bool space3;
    public bool space4;
    public bool space5;
    public bool space6;
    public bool space7;
    public bool space8;
    public bool space9;
    public bool space10;
    public bool space11;
    public bool space12;
    public bool space13;
    public bool space14;
    public bool space15;
    public bool space16;
    public bool space17;
    public bool space18;
    public bool space19;
    public bool space20;
    public bool space21;
    public bool space22;
    public bool space23;
    public bool space24;
    public bool space25;
    public bool space26;
    public bool space27;
    public bool space28;
    public bool space29;
    public bool space30;
    public bool space31;
    public bool space32;
    public bool space33;
    public bool space34;
    public bool space35;
    public bool space36;
    public bool space37;
    public bool space38;
    public bool space39;
    public bool space40;
    public bool space41;
    public bool space42;
    public bool space43;
    public bool space44;
    public bool space45;
    public bool space46;
    public bool space47;
    public bool space48;
    public bool space49;
}
